config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'

  resources :mushrooms
  root to: 'mushrooms#index'
  resources :movies, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  include PgSearch
  pg_search_scope :search_title_syllabus,
    against: [ :title, :syllabus ],
    associated_against: {
      director: [ :first_name, :last_name ]
    }


end

app/models/mushroom.rb
class Mushroom < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?


    before_save :say_hi, if: :will_save_change_to_name?


    def say_hi
          puts 'hi !! '
    end


end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    search_index
      if params[:sort]
        @movies =  @movies.order(params[:sort].to_sym => :asc)
      end
  end




    private


  def search_index
     if params[:query].present?
                sql_query = "
            movies.title @@ :query \
            OR movies.syllabus @@ :query \
            OR directors.first_name @@ :query \
            OR directors.last_name @@ :query \

          "
          @movies = Movie.joins(:director).where(sql_query, query: "%#{params[:query]}%")
          @movies = Movie.search_title_syllabus(params[:query])
       else
          @movies = Movie.all
        end
      end
end

app/controllers/mushrooms_controller.rb
class MushroomsController < ApplicationController
  before_action :set_mushroom, only: [:show, :edit, :update, :destroy]

  # GET /mushrooms
  # GET /mushrooms.json
  def index
    @mushrooms = Mushroom.where.not(latitude: nil, longitude: nil)
    @markers = @mushrooms.map do |shroom|
      {
        lng: shroom.longitude,
        lat: shroom.latitude
      }
    end

  end

  # GET /mushrooms/1
  # GET /mushrooms/1.json
  def show
  end

  # GET /mushrooms/new
  def new
    @mushroom = Mushroom.new
  end

  # GET /mushrooms/1/edit
  def edit
  end

  # POST /mushrooms
  # POST /mushrooms.json
  def create
    @mushroom = Mushroom.new(mushroom_params)

    respond_to do |format|
      if @mushroom.save
        format.html { redirect_to @mushroom, notice: 'Mushroom was successfully created.' }
        format.json { render :show, status: :created, location: @mushroom }
      else
        format.html { render :new }
        format.json { render json: @mushroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mushrooms/1
  # PATCH/PUT /mushrooms/1.json
  def update
    respond_to do |format|
      if @mushroom.update(mushroom_params)
        format.html { redirect_to @mushroom, notice: 'Mushroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @mushroom }
      else
        format.html { render :edit }
        format.json { render json: @mushroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mushrooms/1
  # DELETE /mushrooms/1.json
  def destroy
    @mushroom.destroy
    respond_to do |format|
      format.html { redirect_to mushrooms_url, notice: 'Mushroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mushroom
      @mushroom = Mushroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mushroom_params
      params.require(:mushroom).permit(:name, :address, :country)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
       <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

      <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>

</html>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <%= form_tag movies_path, method: :get do %>
         <%= text_field_tag :query,"",
    class: "form-control",
    placeholder: "Find a movie"
  %>

    <% end %>

      <%= form_for Movie.new,  method: :get do |f|  %>
         <%= hidden_field_tag :sort, :title,
    class: "form-control"
  %>
      <%= f.submit "sort title" %>
    <% end %>

  </div>
  <div class="row">

    <div class="col-sm-8 col-sm-offset-2">
      <div id="movies">
        <% @movies.each do |movie| %>
          <h4><%= movie.title %></h4>
          <p><%= movie.syllabus %></p>
          <p> <%= movie.director.last_name %></p>
          <p> <%= movie.year %> </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/mushrooms/_form.html.erb
<%= simple_form_for(@mushroom) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :country, as: :select, input_html: {  class: "selectpicker countrypicker"  }  %>
    <%= f.input :address%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mushrooms/edit.html.erb
<h1>Editing Mushroom</h1>

<%= render 'form', mushroom: @mushroom %>

<%= link_to 'Show', @mushroom %> |
<%= link_to 'Back', mushrooms_path %>

app/views/mushrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mushrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mushrooms.each do |mushroom| %>
      <tr>
        <td><%= mushroom.name %></td>
        <td><%= mushroom.address %></td>
        <td><%= link_to 'Show', mushroom %></td>
        <td><%= link_to 'Edit', edit_mushroom_path(mushroom) %></td>
        <td><%= link_to 'Destroy', mushroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mushroom', new_mushroom_path %>


<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"

  data-myName="hey my name"
></div>

app/views/mushrooms/new.html.erb
<h1>New Mushroom</h1>

<%= render 'form', mushroom: @mushroom %>

<%= link_to 'Back', mushrooms_path %>

app/views/mushrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mushroom.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @mushroom.address %>
</p>

<%= link_to 'Edit', edit_mushroom_path(@mushroom) %> |
<%= link_to 'Back', mushrooms_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>